project:
  type: website

resources:
  - Userguide.pdf

website:
  title: "Final_Project_VAA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Project
        menu:
          - href: proposal.qmd
            text: Project proposal
          - href: dataprep.qmd
            text: Data preparation
      - text: Shiny App
        menu:
          - href: poster.qmd
            text: Poster
          - href: Userguide.pdf
            text: User guide
          - href: https://dhree.shinyapps.io/world_happiness_shiny/
            text: Visualization
      - text: Meeting records
        menu:
          - href: Minutes of Meeting/minutes_of_meeting.qmd
            text: Meeting Overview
          - href: Minutes of Meeting/meeting1.qmd
            text: Meeting 1
          - href: Minutes of Meeting/meeting2.qmd
            text: Meeting 2
          - href: Minutes of Meeting/meeting3.qmd
            text: Meeting 3
      - href: acknowledgement.qmd
        text: Acknowledgement
      
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

