project:
  type: website

website:
  title: "Final_Project_VAA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Project
        menu:
          - href: proposal.qmd
            text: Project proposal
          - href: dataprep.qmd
            text: Data preparation
          - href: project.qmd
            text: Shiny App
      - text: Meeting records
        menu:
          - href: Minutes of Meeting/minutes_of_meeting.qmd
            text: Meeting Overview
          - href: Minutes of Meeting/meeting1.qmd
            text: Meeting 1
          - href: Minutes of Meeting/meeting2.qmd
            text: Meeting 2
          - href: Minutes of Meeting/meeting3.qmd
            text: Meeting 3
      - href: acknowledgement.qmd
        text: Acknowledgement
      
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

